package com.model;

/**
 * TTea generated by MyEclipse Persistence Tools
 */

public class TChengji implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer stuId;

	private String kecheng;

	private Integer chengji;

	private String del;
	
	private String stuName ;
	
	// Constructors

	public String getStuName() {
		return stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	/** default constructor */
	public TChengji() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStuId() {
		return stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public String getKecheng() {
		return kecheng;
	}

	public void setKecheng(String kecheng) {
		this.kecheng = kecheng;
	}

	public Integer getChengji() {
		return chengji;
	}

	public void setChengji(Integer chengji) {
		this.chengji = chengji;
	}

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}

}