package com.model;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable {

	// Fields

	private Integer id;

	private String xuehao;

	private String name1;

	private String sex;

	private String age;

	private String ruxueshijian;

	private String loginname;

	private String loginpw;

	private Integer tea_id;

	private String del;

	private String shenfenzheng;

	private String zhunkaozheng;

	private String xibie;

	private String nianji;

	// Constructors

	/** default constructor */
	public TUser() {
	}

	/** full constructor */
	public TUser(String xuehao, String name1, String sex, String age,
			String ruxueshijian, String del) {
		this.xuehao = xuehao;
		this.name1 = name1;
		this.sex = sex;
		this.age = age;
		this.ruxueshijian = ruxueshijian;
		this.del = del;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getXuehao() {
		return this.xuehao;
	}

	public Integer getTea_id() {
		return tea_id;
	}

	public void setTea_id(Integer tea_id) {
		this.tea_id = tea_id;
	}

	public void setXuehao(String xuehao) {
		this.xuehao = xuehao;
	}

	public String getName1() {
		return this.name1;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpw() {
		return loginpw;
	}

	public void setLoginpw(String loginpw) {
		this.loginpw = loginpw;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getRuxueshijian() {
		return this.ruxueshijian;
	}

	public void setRuxueshijian(String ruxueshijian) {
		this.ruxueshijian = ruxueshijian;
	}

	public String getDel() {
		return this.del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public String getShenfenzheng() {
		return shenfenzheng;
	}

	public void setShenfenzheng(String shenfenzheng) {
		this.shenfenzheng = shenfenzheng;
	}

	public String getZhunkaozheng() {
		return zhunkaozheng;
	}

	public void setZhunkaozheng(String zhunkaozheng) {
		this.zhunkaozheng = zhunkaozheng;
	}

	public String getXibie() {
		return xibie;
	}

	public void setXibie(String xibie) {
		this.xibie = xibie;
	}

	public String getNianji() {
		return nianji;
	}

	public void setNianji(String nianji) {
		this.nianji = nianji;
	}

}